<li class="listitem ui-state-disabled">
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Custom</a>
            </li>
            <li><a href="#tabs-2">Exactly</a>
            </li>
            <li><a href="#tabs-3">OR/Any</a>
            </li>
            <li><a href="#tabs-4">Exclude</a>
            </li>
            <li><a href="#tabs-5">Number between</a>
            </li>
            <li><a href="#tabs-6">And</a>
            </li>
            <li><a href="#tabs-7">Keyword</a>
            </li>
        </ul>
        <div id="tabs-1">
            <form id="query">
                <input class="ui-corner-all" type="text" />
                <input type="button" value="Add">
            </form>
        </div>
        <div id="tabs-2">
            <p>stuff</p>
        </div>
        <div id="tabs-3">
            <p>stuff</p>
        </div>
        <div id="tabs-4">
            <p>stuff</p>
        </div>
        <div id="tabs-5">
            <p>stuff</p>
        </div>
        <div id="tabs-6">
            <p>stuff</p>
        </div>
        <div id="tabs-7">
            <p>stuff</p>
        </div>
    </div>
</li>
